'use client';
import { useState } from 'react';
import { Download, Upload } from 'lucide-react';

export function KmlToKmzView() {
  const [source, setSource] = useState('<?xml version="1.0"?><kml xmlns="http://www.opengis.net/kml/2.2"><Document><name>Sample map</name></Document></kml>');
  const [status, setStatus] = useState('Paste or upload KML, then create a local KMZ archive.');
  const upload = (e: React.ChangeEvent<HTMLInputElement>) => { const file = e.target.files?.[0]; if (!file) return; const reader = new FileReader(); reader.onload = () => { setSource(String(reader.result || '')); setStatus(`${file.name} loaded.`); }; reader.readAsText(file); };
  const download = () => { try { const xml = new DOMParser().parseFromString(source, 'text/xml'); if (xml.querySelector('parsererror') || xml.documentElement.localName !== 'kml') throw new Error('Enter a valid KML document.'); const archive = createZip('doc.kml', new TextEncoder().encode(source)); const blob = new Blob([archive.buffer as ArrayBuffer], { type: 'application/vnd.google-earth.kmz' }); const a = document.createElement('a'); const url = URL.createObjectURL(blob); a.href = url; a.download = 'map.kmz'; a.click(); URL.revokeObjectURL(url); setStatus('KMZ downloaded.'); } catch (e) { setStatus(e instanceof Error ? e.message : 'Could not create KMZ.'); } };
  return <div className="space-y-5"><div className="rounded-2xl border-2 border-dashed border-navy-200 bg-navy-50/50 p-6 text-center"><label htmlFor="kmz-upload" className="cursor-pointer font-bold text-brand-600"><Upload className="mr-1 inline h-4 w-4" />Upload KML<input id="kmz-upload" type="file" accept=".kml" onChange={upload} className="hidden" /></label><p className="mt-2 text-xs text-navy-500">Processed in browser memory; nothing is uploaded.</p></div><div className="rounded-2xl border border-navy-200 bg-white p-4 shadow-xs"><textarea value={source} onChange={(e) => setSource(e.target.value)} rows={16} className="w-full rounded-xl bg-navy-950 p-3 font-mono text-xs text-navy-100" /><button onClick={download} className="mt-3 w-full rounded-xl bg-brand-600 py-3 text-sm font-bold text-white"><Download className="mr-1 inline h-4 w-4" />Download KMZ</button><p className="mt-2 text-center text-xs text-navy-500" aria-live="polite">{status}</p></div></div>;
}

function createZip(name: string, data: Uint8Array): Uint8Array { const n = new TextEncoder().encode(name); const crc = crc32(data); const header = new Uint8Array(30 + n.length); const h = new DataView(header.buffer); h.setUint32(0, 0x04034b50, true); h.setUint16(4, 20, true); h.setUint32(14, crc, true); h.setUint32(18, data.length, true); h.setUint32(22, data.length, true); h.setUint16(26, n.length, true); header.set(n, 30); const central = new Uint8Array(46 + n.length); const c = new DataView(central.buffer); c.setUint32(0, 0x02014b50, true); c.setUint16(4, 20, true); c.setUint16(6, 20, true); c.setUint32(16, crc, true); c.setUint32(20, data.length, true); c.setUint32(24, data.length, true); c.setUint16(28, n.length, true); central.set(n, 46); const end = new Uint8Array(22); const e = new DataView(end.buffer); e.setUint32(0, 0x06054b50, true); e.setUint16(8, 1, true); e.setUint16(10, 1, true); e.setUint32(12, central.length, true); e.setUint32(16, header.length + data.length, true); const out = new Uint8Array(header.length + data.length + central.length + end.length); out.set(header); out.set(data, header.length); out.set(central, header.length + data.length); out.set(end, header.length + data.length + central.length); return out; }
function crc32(data: Uint8Array) { let crc = 0xffffffff; for (const byte of data) { crc ^= byte; for (let i = 0; i < 8; i++) crc = (crc >>> 1) ^ (0xedb88320 & -(crc & 1)); } return (crc ^ 0xffffffff) >>> 0; }
