/**
 * Geospatial Export Helpers for GeoJSON, KML, GPX, and CSV formats.
 */

export interface ExportGeometry {
  type: 'Point' | 'LineString' | 'Polygon' | 'Circle';
  coordinates: any;
  properties?: Record<string, any>;
}

/**
 * Generates a standard GeoJSON FeatureCollection string.
 */
export function exportToGeoJSON(geometries: ExportGeometry[]): string {
  const features = geometries.map((geom) => {
    let geojsonGeom: any = {
      type: geom.type === 'Circle' ? 'Polygon' : geom.type,
      coordinates: geom.coordinates,
    };

    return {
      type: 'Feature',
      properties: geom.properties || {},
      geometry: geojsonGeom,
    };
  });

  const featureCollection = {
    type: 'FeatureCollection',
    features,
  };

  return JSON.stringify(featureCollection, null, 2);
}

/**
 * Generates an OGC-compliant KML (Keyhole Markup Language) string.
 */
export function exportToKML(geometries: ExportGeometry[], name: string = 'GeoMap Suite Map Export'): string {
  const placemarks = geometries
    .map((geom, idx) => {
      const pName = geom.properties?.name || `Geometry ${idx + 1}`;
      const pDesc = geom.properties?.description || '';

      if (geom.type === 'Point') {
        const [lng, lat] = geom.coordinates;
        return `
    <Placemark>
      <name>${escapeXml(pName)}</name>
      <description>${escapeXml(pDesc)}</description>
      <Point>
        <coordinates>${lng},${lat},0</coordinates>
      </Point>
    </Placemark>`;
      }

      if (geom.type === 'LineString') {
        const coordsStr = geom.coordinates.map((pt: [number, number]) => `${pt[0]},${pt[1]},0`).join(' ');
        return `
    <Placemark>
      <name>${escapeXml(pName)}</name>
      <description>${escapeXml(pDesc)}</description>
      <LineString>
        <tessellate>1</tessellate>
        <coordinates>${coordsStr}</coordinates>
      </LineString>
    </Placemark>`;
      }

      if (geom.type === 'Polygon' || geom.type === 'Circle') {
        const ring = Array.isArray(geom.coordinates[0]) && Array.isArray(geom.coordinates[0][0])
          ? geom.coordinates[0]
          : geom.coordinates;
        const coordsStr = ring.map((pt: [number, number]) => `${pt[0]},${pt[1]},0`).join(' ');
        return `
    <Placemark>
      <name>${escapeXml(pName)}</name>
      <description>${escapeXml(pDesc)}</description>
      <Polygon>
        <outerBoundaryIs>
          <LinearRing>
            <coordinates>${coordsStr}</coordinates>
          </LinearRing>
        </outerBoundaryIs>
      </Polygon>
    </Placemark>`;
      }

      return '';
    })
    .join('\n');

  return `<?xml version="1.0" encoding="UTF-8"?>
<kml xmlns="http://www.opengis.net/kml/2.2">
  <Document>
    <name>${escapeXml(name)}</name>
    <description>Generated by GeoMap Suite Geographic Tools</description>
    ${placemarks}
  </Document>
</kml>`;
}

/**
 * Generates standard GPX 1.1 string for tracks and waypoints.
 */
export function exportToGPX(geometries: ExportGeometry[], name: string = 'GeoMap Suite Track'): string {
  let waypoints = '';
  let trackSegments = '';

  geometries.forEach((geom, idx) => {
    const pName = geom.properties?.name || `Point ${idx + 1}`;

    if (geom.type === 'Point') {
      const [lng, lat] = geom.coordinates;
      waypoints += `  <wpt lat="${lat}" lon="${lng}"><name>${escapeXml(pName)}</name></wpt>\n`;
    } else if (geom.type === 'LineString') {
      const pts = geom.coordinates
        .map((pt: [number, number]) => `      <trkpt lat="${pt[1]}" lon="${pt[0]}"></trkpt>`)
        .join('\n');
      trackSegments += `    <trkseg>\n${pts}\n    </trkseg>\n`;
    }
  });

  return `<?xml version="1.0" encoding="UTF-8"?>
<gpx version="1.1" creator="GeoMap Suite" xmlns="http://www.topografix.com/GPX/1/1">
  <metadata>
    <name>${escapeXml(name)}</name>
    <time>${new Date().toISOString()}</time>
  </metadata>
${waypoints}  <trk>
    <name>${escapeXml(name)}</name>
${trackSegments}  </trk>
</gpx>`;
}

/**
 * Generates CSV string for point features.
 */
export function exportToCSV(geometries: ExportGeometry[]): string {
  const rows: string[] = ['name,latitude,longitude,description,category'];

  geometries.forEach((geom, idx) => {
    const name = `"${(geom.properties?.name || `Point ${idx + 1}`).replace(/"/g, '""')}"`;
    const desc = `"${(geom.properties?.description || '').replace(/"/g, '""')}"`;
    const cat = `"${(geom.properties?.category || '').replace(/"/g, '""')}"`;

    if (geom.type === 'Point') {
      const [lng, lat] = geom.coordinates;
      rows.push(`${name},${lat},${lng},${desc},${cat}`);
    }
  });

  return rows.join('\n');
}

function escapeXml(unsafe: string): string {
  return unsafe.replace(/[<>&'"]/g, (c) => {
    switch (c) {
      case '<': return '&lt;';
      case '>': return '&gt;';
      case '&': return '&amp;';
      case '\'': return '&apos;';
      case '"': return '&quot;';
      default: return c;
    }
  });
}

/**
 * Initiates a client-side file download.
 */
export function downloadFile(content: string, filename: string, mimeType: string = 'text/plain') {
  if (typeof window === 'undefined') return;
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}
