/**
 * Find Nearest National Park Geo Engine
 *
 * Provides a comprehensive directory of all 63 official US National Parks
 * managed by the National Park Service (NPS), along with WGS84 Karney geodesic
 * proximity querying, cardinal bearing calculations, road distance estimates,
 * preset travel hubs, and RFC-4180 CSV export utilities.
 */

import { calculateGeodesic } from './geodesic';

export interface NationalPark {
  id: string;
  name: string;
  fullName: string;
  state: string; // 2-letter state code or multiple e.g. "WY, MT, ID"
  stateFull: string;
  lat: number;
  lng: number;
  establishedYear: number;
  areaAcres: number;
  areaSqKm: number;
  annualVisitors: number; // approximate benchmark
  description: string;
  unescoStatus?: 'World Heritage Site' | 'Biosphere Reserve';
  npsCode: string;
  npsUrl: string;
  highlights: string[];
}

export interface NearestParkResult {
  park: NationalPark;
  distanceMeters: number;
  distanceMiles: number;
  distanceKm: number;
  bearingDegrees: number;
  cardinalBearing: string;
  estimatedDriveMiles: number;
  estimatedDriveHours: number;
}

export interface ParkFilterOptions {
  maxResults?: number;
  maxRadiusMiles?: number;
  state?: string;
  searchQuery?: string;
}

export interface OriginHubPreset {
  id: string;
  name: string;
  state: string;
  lat: number;
  lng: number;
  description: string;
}

/**
 * Complete directory of all 63 official US National Parks
 */
export const US_NATIONAL_PARKS: NationalPark[] = [
  {
    id: 'acadia',
    name: 'Acadia',
    fullName: 'Acadia National Park',
    state: 'ME',
    stateFull: 'Maine',
    lat: 44.35,
    lng: -68.21,
    establishedYear: 1919,
    areaAcres: 49076,
    areaSqKm: 198.6,
    annualVisitors: 3879000,
    description: 'Covering most of Mount Desert Island and associated coastal islands, Acadia features the tallest rocky headlands along the Atlantic coastline.',
    unescoStatus: 'Biosphere Reserve',
    npsCode: 'acad',
    npsUrl: 'https://www.nps.gov/acad/index.htm',
    highlights: ['Cadillac Mountain sunrise', 'Park Loop Road', 'Jordan Pond', 'Precipice Trail', 'Bass Harbor Head Light'],
  },
  {
    id: 'american-samoa',
    name: 'National Park of American Samoa',
    fullName: 'National Park of American Samoa',
    state: 'AS',
    stateFull: 'American Samoa',
    lat: -14.25,
    lng: -170.68,
    establishedYear: 1988,
    areaAcres: 8257,
    areaSqKm: 33.4,
    annualVisitors: 8500,
    description: 'The southernmost US national park spans three Samoan islands, protecting coral reefs, tropical rainforests, and traditional Samoan customs (Fa\'a Samoa).',
    npsCode: 'npsa',
    npsUrl: 'https://www.nps.gov/npsa/index.htm',
    highlights: ['Ofu Beach coral reef', 'Mount Alava trail', 'Flying fox fruit bats', 'Pola Island sea cliffs'],
  },
  {
    id: 'arches',
    name: 'Arches',
    fullName: 'Arches National Park',
    state: 'UT',
    stateFull: 'Utah',
    lat: 38.68,
    lng: -109.57,
    establishedYear: 1971,
    areaAcres: 76679,
    areaSqKm: 310.3,
    annualVisitors: 1482000,
    description: 'Contains over 2,000 cataloged natural sandstone arches, pinnacles, balanced rocks, and sandstone fins in the high desert of the Colorado Plateau.',
    npsCode: 'arch',
    npsUrl: 'https://www.nps.gov/arch/index.htm',
    highlights: ['Delicate Arch', 'Landscape Arch', 'Devils Garden', 'Balanced Rock', 'Fiery Furnace'],
  },
  {
    id: 'badlands',
    name: 'Badlands',
    fullName: 'Badlands National Park',
    state: 'SD',
    stateFull: 'South Dakota',
    lat: 43.75,
    lng: -102.5,
    establishedYear: 1978,
    areaAcres: 242756,
    areaSqKm: 982.4,
    annualVisitors: 910000,
    description: 'Striking eroded buttes, pinnacles, and spires blend with the largest undisturbed mixed-grass prairie in the United States, rich in Oligocene mammal fossils.',
    npsCode: 'badl',
    npsUrl: 'https://www.nps.gov/badl/index.htm',
    highlights: ['Badlands Loop Road', 'Notch Trail', 'Fossil Exhibit Trail', 'Yellow Mounds Overlook', 'Bison & bighorn sheep'],
  },
  {
    id: 'big-bend',
    name: 'Big Bend',
    fullName: 'Big Bend National Park',
    state: 'TX',
    stateFull: 'Texas',
    lat: 29.25,
    lng: -103.25,
    establishedYear: 1944,
    areaAcres: 801163,
    areaSqKm: 3242.2,
    annualVisitors: 515000,
    description: 'Named for the prominent bend in the Rio Grande along the US-Mexico border, preserving rugged Chihuahuan Desert, the Chisos Mountains, and deep river canyons.',
    unescoStatus: 'Biosphere Reserve',
    npsCode: 'bibe',
    npsUrl: 'https://www.nps.gov/bibe/index.htm',
    highlights: ['Santa Elena Canyon', 'Lost Mine Trail', 'South Rim Chisos', 'Hot Springs Historic District', 'International Dark Sky Sanctuary'],
  },
  {
    id: 'biscayne',
    name: 'Biscayne',
    fullName: 'Biscayne National Park',
    state: 'FL',
    stateFull: 'Florida',
    lat: 25.47,
    lng: -80.22,
    establishedYear: 1980,
    areaAcres: 172971,
    areaSqKm: 699.9,
    annualVisitors: 700000,
    description: 'Located south of Miami, 95% of the park is underwater, preserving Biscayne Bay, northern Florida Keys, and extensive offshore coral barrier reefs.',
    npsCode: 'bisc',
    npsUrl: 'https://www.nps.gov/bisc/index.htm',
    highlights: ['Maritime Heritage Trail shipwrecks', 'Boca Chita Key Lighthouse', 'Coral reef snorkeling', 'Mangrove shoreline paddling'],
  },
  {
    id: 'black-canyon-of-the-gunnison',
    name: 'Black Canyon of the Gunnison',
    fullName: 'Black Canyon of the Gunnison National Park',
    state: 'CO',
    stateFull: 'Colorado',
    lat: 38.57,
    lng: -107.72,
    establishedYear: 1999,
    areaAcres: 30779,
    areaSqKm: 124.6,
    annualVisitors: 308000,
    description: 'Protects 12 miles of the deeply carved, steep, and shadowed canyon of the Gunnison River, featuring some of the steepest cliff faces in North America.',
    npsCode: 'blca',
    npsUrl: 'https://www.nps.gov/blca/index.htm',
    highlights: ['Painted Wall cliff (2,250 ft)', 'South Rim Road scenic drive', 'Gunnison Point', 'Chasm View', 'Dark sky stargazing'],
  },
  {
    id: 'bryce-canyon',
    name: 'Bryce Canyon',
    fullName: 'Bryce Canyon National Park',
    state: 'UT',
    stateFull: 'Utah',
    lat: 37.57,
    lng: -112.18,
    establishedYear: 1928,
    areaAcres: 35835,
    areaSqKm: 145.0,
    annualVisitors: 2350000,
    description: 'A giant natural amphitheater along the Paunsaugunt Plateau famous for having the largest collection of hoodoos (irregular rock columns) anywhere in the world.',
    npsCode: 'brca',
    npsUrl: 'https://www.nps.gov/brca/index.htm',
    highlights: ['Bryce Amphitheater', 'Queens Garden / Navajo Loop', 'Inspiration Point', 'Thor\'s Hammer', 'Sunrise & Sunset Points'],
  },
  {
    id: 'canyonlands',
    name: 'Canyonlands',
    fullName: 'Canyonlands National Park',
    state: 'UT',
    stateFull: 'Utah',
    lat: 38.2,
    lng: -109.93,
    establishedYear: 1964,
    areaAcres: 337597,
    areaSqKm: 1366.2,
    annualVisitors: 780000,
    description: 'Preserves a colorful wilderness eroded into innumerable canyons, mesas, and buttes by the Colorado and Green rivers, divided into four distinct districts.',
    npsCode: 'cany',
    npsUrl: 'https://www.nps.gov/cany/index.htm',
    highlights: ['Mesa Arch sunrise', 'Island in the Sky vista', 'The Needles district', 'Green River Overlook', 'White Rim Trail'],
  },
  {
    id: 'capitol-reef',
    name: 'Capitol Reef',
    fullName: 'Capitol Reef National Park',
    state: 'UT',
    stateFull: 'Utah',
    lat: 38.2,
    lng: -111.17,
    establishedYear: 1971,
    areaAcres: 241904,
    areaSqKm: 979.0,
    annualVisitors: 1227000,
    description: 'Highlights the Waterpocket Fold, a nearly 100-mile-long monocline (wrinkle in the Earth\'s crust), with white Navajo sandstone domes resembling capitol buildings.',
    npsCode: 'care',
    npsUrl: 'https://www.nps.gov/care/index.htm',
    highlights: ['Fruita historic orchards & Gifford House', 'Cassidy Arch', 'Hickman Bridge', 'Scenic Drive & Capitol Gorge', 'Cathedral Valley'],
  },
  {
    id: 'carlsbad-caverns',
    name: 'Carlsbad Caverns',
    fullName: 'Carlsbad Caverns National Park',
    state: 'NM',
    stateFull: 'New Mexico',
    lat: 32.17,
    lng: -104.44,
    establishedYear: 1930,
    areaAcres: 46766,
    areaSqKm: 189.3,
    annualVisitors: 390000,
    description: 'Features more than 119 known caves formed by sulfuric acid dissolving Permian-age limestone, including the massive 4,000-foot-long Big Room.',
    unescoStatus: 'World Heritage Site',
    npsCode: 'cave',
    npsUrl: 'https://www.nps.gov/cave/index.htm',
    highlights: ['The Big Room limestone chamber', 'Natural Entrance trail', 'Bat Flight evening program', 'King\'s Palace tour', 'Slaughter Canyon Cave'],
  },
  {
    id: 'channel-islands',
    name: 'Channel Islands',
    fullName: 'Channel Islands National Park',
    state: 'CA',
    stateFull: 'California',
    lat: 34.01,
    lng: -119.42,
    establishedYear: 1980,
    areaAcres: 249561,
    areaSqKm: 1009.9,
    annualVisitors: 320000,
    description: 'Encompasses five isolated islands off the coast of Southern California, preserving unique endemic wildlife such as the island fox and rich giant kelp forests.',
    unescoStatus: 'Biosphere Reserve',
    npsCode: 'chis',
    npsUrl: 'https://www.nps.gov/chis/index.htm',
    highlights: ['Santa Cruz Island sea kayaking', 'Anacapa Island lighthouse & cliffs', 'Island fox spotting', 'Scuba diving kelp forests', 'Inspiration Point'],
  },
  {
    id: 'congaree',
    name: 'Congaree',
    fullName: 'Congaree National Park',
    state: 'SC',
    stateFull: 'South Carolina',
    lat: 33.78,
    lng: -80.78,
    establishedYear: 2003,
    areaAcres: 26276,
    areaSqKm: 106.3,
    annualVisitors: 215000,
    description: 'Protects the largest contiguous tract of old-growth bottomland hardwood forest left in the southeastern United States along the Congaree River.',
    unescoStatus: 'Biosphere Reserve',
    npsCode: 'cong',
    npsUrl: 'https://www.nps.gov/cong/index.htm',
    highlights: ['Boardwalk Loop Trail', 'Cedar Creek canoe trail', 'Synchronous fireflies event (May/June)', 'Champion old-growth loblolly pines'],
  },
  {
    id: 'crater-lake',
    name: 'Crater Lake',
    fullName: 'Crater Lake National Park',
    state: 'OR',
    stateFull: 'Oregon',
    lat: 42.94,
    lng: -122.1,
    establishedYear: 1902,
    areaAcres: 183224,
    areaSqKm: 741.5,
    annualVisitors: 550000,
    description: 'Occupies the caldera of collapsed Mount Mazama volcano, filled with rain and snow to form the deepest lake in the United States (1,943 ft) with intense sapphire clarity.',
    npsCode: 'crla',
    npsUrl: 'https://www.nps.gov/crla/index.htm',
    highlights: ['Rim Drive scenic loop', 'Wizard Island boat tour', 'Garfield Peak trail', 'Cleetwood Cove trail (lake access)', 'Watchman Overlook'],
  },
  {
    id: 'cuyahoga-valley',
    name: 'Cuyahoga Valley',
    fullName: 'Cuyahoga Valley National Park',
    state: 'OH',
    stateFull: 'Ohio',
    lat: 41.24,
    lng: -81.55,
    establishedYear: 2000,
    areaAcres: 32572,
    areaSqKm: 131.8,
    annualVisitors: 2860000,
    description: 'Follows the winding Cuyahoga River between Cleveland and Akron, preserving rolling forested river valleys, historic canal locks, and dramatic sandstone ledges.',
    npsCode: 'cuva',
    npsUrl: 'https://www.nps.gov/cuva/index.htm',
    highlights: ['Brandywine Falls (65 ft)', 'The Ledges trail & overlook', 'Ohio & Erie Canal Towpath Trail', 'Cuyahoga Valley Scenic Railroad', 'Beaver Marsh'],
  },
  {
    id: 'death-valley',
    name: 'Death Valley',
    fullName: 'Death Valley National Park',
    state: 'CA, NV',
    stateFull: 'California, Nevada',
    lat: 36.53,
    lng: -116.93,
    establishedYear: 1994,
    areaAcres: 3408407,
    areaSqKm: 13793.3,
    annualVisitors: 1100000,
    description: 'The hottest, driest, and lowest national park in North America, featuring Badwater Basin (-282 ft elevation), expansive sand dunes, and colorful badlands.',
    unescoStatus: 'Biosphere Reserve',
    npsCode: 'deva',
    npsUrl: 'https://www.nps.gov/deva/index.htm',
    highlights: ['Badwater Basin salt flats', 'Zabriskie Point sunrise', 'Mesquite Flat Sand Dunes', 'Artist\'s Palette drive', 'Dante\'s View panorama'],
  },
  {
    id: 'denali',
    name: 'Denali',
    fullName: 'Denali National Park and Preserve',
    state: 'AK',
    stateFull: 'Alaska',
    lat: 63.33,
    lng: -150.5,
    establishedYear: 1917,
    areaAcres: 4740911,
    areaSqKm: 19185.8,
    annualVisitors: 490000,
    description: 'Surrounds Denali (Mount McKinley), the tallest peak in North America at 20,310 feet, offering 6 million acres of subarctic tundra, glaciers, and grizzly bears.',
    unescoStatus: 'Biosphere Reserve',
    npsCode: 'dena',
    npsUrl: 'https://www.nps.gov/dena/index.htm',
    highlights: ['Denali summit view', 'Park Road bus transit', 'Big Five wildlife spotting', 'Savage River loop', 'Eielson Visitor Center'],
  },
  {
    id: 'dry-tortugas',
    name: 'Dry Tortugas',
    fullName: 'Dry Tortugas National Park',
    state: 'FL',
    stateFull: 'Florida',
    lat: 24.63,
    lng: -82.87,
    establishedYear: 1992,
    areaAcres: 64701,
    areaSqKm: 261.8,
    annualVisitors: 80000,
    description: 'Located 70 miles west of Key West in the Gulf of Mexico, centered around massive 19th-century brick Fort Jefferson and pristine coral reefs reachable by ferry/seaplane.',
    unescoStatus: 'Biosphere Reserve',
    npsCode: 'drto',
    npsUrl: 'https://www.nps.gov/drto/index.htm',
    highlights: ['Historic Fort Jefferson masonry', 'Snorkeling coral moats', 'Bush Key bird sanctuary', 'Seaplane aerial crossing'],
  },
  {
    id: 'everglades',
    name: 'Everglades',
    fullName: 'Everglades National Park',
    state: 'FL',
    stateFull: 'Florida',
    lat: 25.74,
    lng: -80.55,
    establishedYear: 1947,
    areaAcres: 1508969,
    areaSqKm: 6106.6,
    annualVisitors: 1155000,
    description: 'The largest subtropical wilderness in the United States, protecting a vast "River of Grass" ecosystem home to alligators, crocodiles, manatees, and Florida panthers.',
    unescoStatus: 'World Heritage Site',
    npsCode: 'ever',
    npsUrl: 'https://www.nps.gov/ever/index.htm',
    highlights: ['Anhinga Trail wildlife boardwalk', 'Shark Valley tram & observation tower', 'Flamingo Marina kayak trails', 'Gulf Coast Ten Thousand Islands'],
  },
  {
    id: 'gates-of-the-arctic',
    name: 'Gates of the Arctic',
    fullName: 'Gates of the Arctic National Park and Preserve',
    state: 'AK',
    stateFull: 'Alaska',
    lat: 67.78,
    lng: -153.3,
    establishedYear: 1980,
    areaAcres: 7523897,
    areaSqKm: 30448.1,
    annualVisitors: 10000,
    description: 'The northernmost US national park, a roadless and trail-free wilderness entirely above the Arctic Circle in the Brooks Range, traversed by caribou herds.',
    npsCode: 'gaar',
    npsUrl: 'https://www.nps.gov/gaar/index.htm',
    highlights: ['Arrigetch Peaks granite spires', 'Noatak & Alatna wild rivers', 'Caribou migration routes', 'True pathless wilderness trekking'],
  },
  {
    id: 'gateway-arch',
    name: 'Gateway Arch',
    fullName: 'Gateway Arch National Park',
    state: 'MO',
    stateFull: 'Missouri',
    lat: 38.62,
    lng: -90.18,
    establishedYear: 2018,
    areaAcres: 91,
    areaSqKm: 0.4,
    annualVisitors: 2420000,
    description: 'The smallest national park in the country, honoring Thomas Jefferson\'s vision of the continental United States and pioneers of the Lewis and Clark Expedition.',
    npsCode: 'gear',
    npsUrl: 'https://www.nps.gov/gear/index.htm',
    highlights: ['630-foot stainless steel Arch tram ride', 'Museum of Westward Expansion', 'Old Courthouse (Dred Scott site)', 'Mississippi riverfront plaza'],
  },
  {
    id: 'glacier',
    name: 'Glacier',
    fullName: 'Glacier National Park',
    state: 'MT',
    stateFull: 'Montana',
    lat: 48.8,
    lng: -114.0,
    establishedYear: 1910,
    areaAcres: 1017001,
    areaSqKm: 4115.6,
    annualVisitors: 3000000,
    description: 'Known as the "Crown of the Continent," featuring dramatic glacially carved alpine peaks, over 700 lakes, active glaciers, and the engineering marvel Going-to-the-Sun Road.',
    unescoStatus: 'World Heritage Site',
    npsCode: 'glac',
    npsUrl: 'https://www.nps.gov/glac/index.htm',
    highlights: ['Going-to-the-Sun Road scenic drive', 'Logan Pass & Highline Trail', 'Grinnell Glacier hike', 'Lake McDonald colorful pebbles', 'Many Glacier valley'],
  },
  {
    id: 'glacier-bay',
    name: 'Glacier Bay',
    fullName: 'Glacier Bay National Park and Preserve',
    state: 'AK',
    stateFull: 'Alaska',
    lat: 58.5,
    lng: -137.0,
    establishedYear: 1980,
    areaAcres: 3223384,
    areaSqKm: 13044.6,
    annualVisitors: 650000,
    description: 'Encompasses tidewater glaciers, snow-capped mountain ranges, ocean fjords, and temperate rainforest along Alaska\'s Inside Passage, rich in marine life.',
    unescoStatus: 'World Heritage Site',
    npsCode: 'glba',
    npsUrl: 'https://www.nps.gov/glba/index.htm',
    highlights: ['Margerie Glacier calving', 'Humpback whale & sea otter sightings', 'Bartlett Cove kayak expedition', 'Fairweather Mountain Range'],
  },
  {
    id: 'grand-canyon',
    name: 'Grand Canyon',
    fullName: 'Grand Canyon National Park',
    state: 'AZ',
    stateFull: 'Arizona',
    lat: 36.06,
    lng: -112.14,
    establishedYear: 1919,
    areaAcres: 1201647,
    areaSqKm: 4862.9,
    annualVisitors: 4730000,
    description: 'A world-famous mile-deep gorge carved by the Colorado River, exposing nearly two billion years of Earth\'s geological history across vibrant rock layers.',
    unescoStatus: 'World Heritage Site',
    npsCode: 'grca',
    npsUrl: 'https://www.nps.gov/grca/index.htm',
    highlights: ['South Rim Mather Point & Bright Angel Trail', 'Desert View Watchtower', 'North Rim scenic lodge', 'Phantom Ranch river canyon', 'Hopi Point sunset'],
  },
  {
    id: 'grand-teton',
    name: 'Grand Teton',
    fullName: 'Grand Teton National Park',
    state: 'WY',
    stateFull: 'Wyoming',
    lat: 43.73,
    lng: -110.8,
    establishedYear: 1929,
    areaAcres: 310044,
    areaSqKm: 1254.7,
    annualVisitors: 3400000,
    description: 'The abrupt, jagged peaks of the Teton Range rise dramatically without foothills over the alpine valley of Jackson Hole and glacial lakes like Jenny Lake.',
    npsCode: 'grte',
    npsUrl: 'https://www.nps.gov/grte/index.htm',
    highlights: ['Jenny Lake & Cascade Canyon trail', 'Mormon Row historic barns', 'Snake River Overlook (Ansel Adams)', 'Oxbow Bend reflection', 'Signal Mountain summit'],
  },
  {
    id: 'great-basin',
    name: 'Great Basin',
    fullName: 'Great Basin National Park',
    state: 'NV',
    stateFull: 'Nevada',
    lat: 38.98,
    lng: -114.3,
    establishedYear: 1986,
    areaAcres: 77180,
    areaSqKm: 312.3,
    annualVisitors: 140000,
    description: 'Centering on 13,063-foot Wheeler Peak, the park preserves 5,000-year-old ancient Bristlecone Pines, Lehman Caves, and some of the darkest night skies in North America.',
    npsCode: 'grba',
    npsUrl: 'https://www.nps.gov/grba/index.htm',
    highlights: ['Bristlecone Pine grove (Prometheus)', 'Lehman Caves stalactite tours', 'Wheeler Peak scenic drive & glacier', 'Stella Lake alpine reflection'],
  },
  {
    id: 'great-sand-dunes',
    name: 'Great Sand Dunes',
    fullName: 'Great Sand Dunes National Park and Preserve',
    state: 'CO',
    stateFull: 'Colorado',
    lat: 37.73,
    lng: -105.51,
    establishedYear: 2004,
    areaAcres: 107342,
    areaSqKm: 434.4,
    annualVisitors: 512000,
    description: 'Contains the tallest sand dunes in North America, rising up to 750 feet against the backdrop of the rugged Sangre de Cristo Mountains in the San Luis Valley.',
    npsCode: 'grsa',
    npsUrl: 'https://www.nps.gov/grsa/index.htm',
    highlights: ['Star Dune & High Dune climbs', 'Sandboarding & sandsledding', 'Medano Creek seasonal beach', 'Medano Pass 4WD primitive road'],
  },
  {
    id: 'great-smoky-mountains',
    name: 'Great Smoky Mountains',
    fullName: 'Great Smoky Mountains National Park',
    state: 'NC, TN',
    stateFull: 'North Carolina, Tennessee',
    lat: 35.68,
    lng: -83.53,
    establishedYear: 1934,
    areaAcres: 522427,
    areaSqKm: 2114.2,
    annualVisitors: 12940000,
    description: 'America\'s most visited national park spans the Appalachian Mountains, world-renowned for its biological diversity, ancient mountains, and historic pioneer cabins.',
    unescoStatus: 'World Heritage Site',
    npsCode: 'grsm',
    npsUrl: 'https://www.nps.gov/grsm/index.htm',
    highlights: ['Clingmans Dome observation tower (6,643 ft)', 'Cades Cove scenic loop & wildlife', 'Roaring Fork Motor Nature Trail', 'Appalachian Trail ridge walk', 'Laurel Falls'],
  },
  {
    id: 'guadalupe-mountains',
    name: 'Guadalupe Mountains',
    fullName: 'Guadalupe Mountains National Park',
    state: 'TX',
    stateFull: 'Texas',
    lat: 31.92,
    lng: -104.87,
    establishedYear: 1972,
    areaAcres: 86367,
    areaSqKm: 349.5,
    annualVisitors: 220000,
    description: 'Preserves the world\'s premier example of an ancient, fossilized Permian reef, featuring Guadalupe Peak (8,751 ft, highest point in Texas) and lush McKittrick Canyon.',
    npsCode: 'gumo',
    npsUrl: 'https://www.nps.gov/gumo/index.htm',
    highlights: ['Guadalupe Peak summit hike', 'McKittrick Canyon fall foliage', 'El Capitan limestone monolith', 'Devil\'s Hall trail'],
  },
  {
    id: 'haleakala',
    name: 'Haleakalā',
    fullName: 'Haleakalā National Park',
    state: 'HI',
    stateFull: 'Hawaii',
    lat: 20.72,
    lng: -156.17,
    establishedYear: 1961,
    areaAcres: 33265,
    areaSqKm: 134.6,
    annualVisitors: 850000,
    description: 'Dominates the island of Maui with the massive 10,023-foot summit caldera of dormant volcano Haleakalā, offering crater trails, nēnē geese, and coastal waterfalls at Kīpahulu.',
    unescoStatus: 'Biosphere Reserve',
    npsCode: 'hale',
    npsUrl: 'https://www.nps.gov/hale/index.htm',
    highlights: ['Summit sunrise above the cloud inversion', 'Sliding Sands (Keonehe\'ehe\'e) trail', 'Pipiwai Trail bamboo forest & Waimoku Falls', 'Seven Sacred Pools (Ohe\'o Gulch)'],
  },
  {
    id: 'hawaii-volcanoes',
    name: 'Hawaiʻi Volcanoes',
    fullName: 'Hawaiʻi Volcanoes National Park',
    state: 'HI',
    stateFull: 'Hawaii',
    lat: 19.38,
    lng: -155.2,
    establishedYear: 1916,
    areaAcres: 325605,
    areaSqKm: 1317.7,
    annualVisitors: 1580000,
    description: 'Encompasses two of the world\'s most active volcanoes: Kīlauea and Mauna Loa, displaying active lava flows, caldera steam vents, and lush fern rainforests.',
    unescoStatus: 'World Heritage Site',
    npsCode: 'havo',
    npsUrl: 'https://www.nps.gov/havo/index.htm',
    highlights: ['Kīlauea Caldera glow & Halemaʻumaʻu', 'Crater Rim Drive', 'Nāhuku (Thurston Lava Tube)', 'Chain of Craters Road to the sea', 'Kīlauea Iki trail'],
  },
  {
    id: 'hot-springs',
    name: 'Hot Springs',
    fullName: 'Hot Springs National Park',
    state: 'AR',
    stateFull: 'Arkansas',
    lat: 34.51,
    lng: -93.05,
    establishedYear: 1921,
    areaAcres: 5550,
    areaSqKm: 22.5,
    annualVisitors: 2600000,
    description: 'Surrounds the historic city of Hot Springs, Arkansas, preserving 47 thermal mineral springs flowing from the Ouachita Mountains and gilded Age-era Bathhouse Row.',
    npsCode: 'hosp',
    npsUrl: 'https://www.nps.gov/hosp/index.htm',
    highlights: ['Bathhouse Row historic architecture', 'Buckstaff & Quapaw thermal baths', 'Hot Springs Mountain Tower', 'Grand Promenade trail', 'Display thermal springs'],
  },
  {
    id: 'indiana-dunes',
    name: 'Indiana Dunes',
    fullName: 'Indiana Dunes National Park',
    state: 'IN',
    stateFull: 'Indiana',
    lat: 41.65,
    lng: -87.05,
    establishedYear: 2019,
    areaAcres: 15349,
    areaSqKm: 62.1,
    annualVisitors: 2800000,
    description: 'Hugs 15 miles of the southern Lake Michigan shoreline, featuring towering sand dunes, bogs, prairies, oak savannas, and rich botanical biodiversity.',
    npsCode: 'indu',
    npsUrl: 'https://www.nps.gov/indu/index.htm',
    highlights: ['3 Dune Challenge (Mount Jackson, Holden, Tom)', 'West Beach & Diana Dunes trail', 'Cowles Bog National Natural Landmark', 'Lake Michigan sunset with Chicago skyline'],
  },
  {
    id: 'isle-royale',
    name: 'Isle Royale',
    fullName: 'Isle Royale National Park',
    state: 'MI',
    stateFull: 'Michigan',
    lat: 47.97,
    lng: -89.17,
    establishedYear: 1940,
    areaAcres: 571790,
    areaSqKm: 2314.0,
    annualVisitors: 26000,
    description: 'An isolated wilderness archipelago in northern Lake Superior reachable only by boat or seaplane, renowned for its famous long-term ecological wolf and moose study.',
    unescoStatus: 'Biosphere Reserve',
    npsCode: 'isro',
    npsUrl: 'https://www.nps.gov/isro/index.htm',
    highlights: ['Greenstone Ridge Trail (40 mi)', 'Rock Harbor & Windigo ports', 'Scuba diving cold shipwrecks', 'Paddling inland chain of lakes'],
  },
  {
    id: 'joshua-tree',
    name: 'Joshua Tree',
    fullName: 'Joshua Tree National Park',
    state: 'CA',
    stateFull: 'California',
    lat: 33.79,
    lng: -115.9,
    establishedYear: 1994,
    areaAcres: 792623,
    areaSqKm: 3207.6,
    annualVisitors: 3058000,
    description: 'Straddles the Mojave and Colorado desert ecosystems, characterized by quirky Joshua trees (Yucca brevifolia) and massive weathered granite boulder formations.',
    unescoStatus: 'Biosphere Reserve',
    npsCode: 'jotr',
    npsUrl: 'https://www.nps.gov/jotr/index.htm',
    highlights: ['Hidden Valley bouldering loop', 'Keys View panorama of San Andreas Fault', 'Skull Rock', 'Cholla Cactus Garden', 'Barker Dam'],
  },
  {
    id: 'katmai',
    name: 'Katmai',
    fullName: 'Katmai National Park and Preserve',
    state: 'AK',
    stateFull: 'Alaska',
    lat: 58.5,
    lng: -155.0,
    establishedYear: 1980,
    areaAcres: 3674529,
    areaSqKm: 14870.3,
    annualVisitors: 34000,
    description: 'Located on the Alaska Peninsula, famous for Brooks Falls salmon runs where dozens of coastal brown bears fish, and the volcanic Valley of Ten Thousand Smokes.',
    npsCode: 'katm',
    npsUrl: 'https://www.nps.gov/katm/index.htm',
    highlights: ['Brooks Falls brown bear salmon catching', 'Valley of Ten Thousand Smokes ashflow', 'Naknek Lake floatplane landing', 'Fat Bear Week celebration'],
  },
  {
    id: 'kenai-fjords',
    name: 'Kenai Fjords',
    fullName: 'Kenai Fjords National Park',
    state: 'AK',
    stateFull: 'Alaska',
    lat: 59.92,
    lng: -149.65,
    establishedYear: 1980,
    areaAcres: 669650,
    areaSqKm: 2710.0,
    annualVisitors: 412000,
    description: 'Showcases the vast 700-square-mile Harding Icefield and nearly 40 outflowing glaciers carving deep, dramatic ocean fjords brimming with marine wildlife.',
    npsCode: 'kefj',
    npsUrl: 'https://www.nps.gov/kefj/index.htm',
    highlights: ['Exit Glacier roadside hike', 'Harding Icefield strenuous trail', 'Resurrection Bay fjord boat cruise', 'Orcas, puffins, and sea otters'],
  },
  {
    id: 'kings-canyon',
    name: 'Kings Canyon',
    fullName: 'Kings Canyon National Park',
    state: 'CA',
    stateFull: 'California',
    lat: 36.8,
    lng: -118.55,
    establishedYear: 1940,
    areaAcres: 461901,
    areaSqKm: 1869.2,
    annualVisitors: 640000,
    description: 'Preserves the towering General Grant Tree (the nation\'s Christmas Tree), deep glacier-carved Kings Canyon, granite peaks, and roaring rivers of the High Sierra.',
    unescoStatus: 'Biosphere Reserve',
    npsCode: 'kica',
    npsUrl: 'https://www.nps.gov/seki/index.htm',
    highlights: ['General Grant Grove', 'Kings Canyon Scenic Byway drive', 'Roaring River Falls', 'Mist Falls trail into the canyon', 'Zumwalt Meadow'],
  },
  {
    id: 'kobuk-valley',
    name: 'Kobuk Valley',
    fullName: 'Kobuk Valley National Park',
    state: 'AK',
    stateFull: 'Alaska',
    lat: 67.55,
    lng: -159.28,
    establishedYear: 1980,
    areaAcres: 1750716,
    areaSqKm: 7084.9,
    annualVisitors: 17000,
    description: 'Contains the Great Kobuk Sand Dunes (the largest active high-latitude sand dunes in North America) and protects the caribou crossing along the Kobuk River.',
    npsCode: 'kova',
    npsUrl: 'https://www.nps.gov/kova/index.htm',
    highlights: ['Great Kobuk Sand Dunes (25 sq mi)', 'Western Arctic caribou migration', 'Onion Portage archaeological site', 'Wild Kobuk River packrafting'],
  },
  {
    id: 'lake-clark',
    name: 'Lake Clark',
    fullName: 'Lake Clark National Park and Preserve',
    state: 'AK',
    stateFull: 'Alaska',
    lat: 60.97,
    lng: -153.42,
    establishedYear: 1980,
    areaAcres: 2619816,
    areaSqKm: 10602.0,
    annualVisitors: 18000,
    description: 'Where three mountain ranges collide, featuring active volcanoes Redoubt and Iliamna, turquoise glacial lakes, wild salmon rivers, and coastal brown bears.',
    npsCode: 'lacl',
    npsUrl: 'https://www.nps.gov/lacl/index.htm',
    highlights: ['Dick Proenneke\'s historic cabin at Twin Lakes', 'Port Alsworth floatplane base', 'Chinitna Bay bear viewing', 'Lake Clark turquoise waters'],
  },
  {
    id: 'lassen-volcanic',
    name: 'Lassen Volcanic',
    fullName: 'Lassen Volcanic National Park',
    state: 'CA',
    stateFull: 'California',
    lat: 40.49,
    lng: -121.51,
    establishedYear: 1916,
    areaAcres: 106589,
    areaSqKm: 431.3,
    annualVisitors: 450000,
    description: 'One of the few places on Earth where all four types of volcanoes (plug dome, shield, cinder cone, and stratovolcano) exist alongside boiling mud pots and steam vents.',
    npsCode: 'lavo',
    npsUrl: 'https://www.nps.gov/lavo/index.htm',
    highlights: ['Bumpass Hell hydrothermal boardwalk', 'Lassen Peak summit trail (10,457 ft)', 'Manzanita Lake reflection', 'Cinder Cone & Fantastic Lava Beds'],
  },
  {
    id: 'mammoth-cave',
    name: 'Mammoth Cave',
    fullName: 'Mammoth Cave National Park',
    state: 'KY',
    stateFull: 'Kentucky',
    lat: 37.18,
    lng: -86.1,
    establishedYear: 1941,
    areaAcres: 54011,
    areaSqKm: 218.6,
    annualVisitors: 660000,
    description: 'The world\'s longest known subterranean cave system, with more than 426 miles of surveyed passageways carved into Mississippian limestone strata.',
    unescoStatus: 'World Heritage Site',
    npsCode: 'maca',
    npsUrl: 'https://www.nps.gov/maca/index.htm',
    highlights: ['Historic Domes & Dripstones tour', 'Frozen Niagara formation', 'Gothic Avenue historic signatures', 'Green River aboveground kayaking'],
  },
  {
    id: 'mesa-verde',
    name: 'Mesa Verde',
    fullName: 'Mesa Verde National Park',
    state: 'CO',
    stateFull: 'Colorado',
    lat: 37.18,
    lng: -108.49,
    establishedYear: 1906,
    areaAcres: 52485,
    areaSqKm: 212.4,
    annualVisitors: 505000,
    description: 'Protects nearly 5,000 archaeological sites, including 600 incredibly preserved Ancestral Puebloan cliff dwellings constructed in canyon alcoves between 600 and 1300 AD.',
    unescoStatus: 'World Heritage Site',
    npsCode: 'meve',
    npsUrl: 'https://www.nps.gov/meve/index.htm',
    highlights: ['Cliff Palace guided tour', 'Balcony House ladder climb', 'Long House on Wetherill Mesa', 'Spruce Tree House', 'Mesa Top Loop drive'],
  },
  {
    id: 'mount-rainier',
    name: 'Mount Rainier',
    fullName: 'Mount Rainier National Park',
    state: 'WA',
    stateFull: 'Washington',
    lat: 46.85,
    lng: -121.75,
    establishedYear: 1899,
    areaAcres: 236381,
    areaSqKm: 956.6,
    annualVisitors: 1620000,
    description: 'An iconic active stratovolcano rising to 14,411 feet, carrying 25 major named glaciers and surrounded by subalpine wildflower meadows and old-growth cedar forests.',
    npsCode: 'mora',
    npsUrl: 'https://www.nps.gov/mora/index.htm',
    highlights: ['Paradise wildflower meadows & Skyline Trail', 'Sunrise Point (6,400 ft highest drive)', 'Reflection Lakes', 'Wonderland Trail (93 mi circumnavigation)', 'Narada & Christine Falls'],
  },
  {
    id: 'new-river-gorge',
    name: 'New River Gorge',
    fullName: 'New River Gorge National Park and Preserve',
    state: 'WV',
    stateFull: 'West Virginia',
    lat: 37.96,
    lng: -81.08,
    establishedYear: 2020,
    areaAcres: 72808,
    areaSqKm: 294.6,
    annualVisitors: 1600000,
    description: 'America\'s 63rd national park preserves the rugged canyon carved by one of the continent\'s oldest rivers, famous for world-class whitewater rafting and rock climbing.',
    npsCode: 'neri',
    npsUrl: 'https://www.nps.gov/neri/index.htm',
    highlights: ['New River Gorge Bridge walk & Bridge Day', 'Grandview overlook', 'Long Point trail vista', 'Endless Wall climbing crags', 'Thurmond ghost town'],
  },
  {
    id: 'north-cascades',
    name: 'North Cascades',
    fullName: 'North Cascades National Park',
    state: 'WA',
    stateFull: 'Washington',
    lat: 48.7,
    lng: -121.2,
    establishedYear: 1968,
    areaAcres: 504780,
    areaSqKm: 2042.8,
    annualVisitors: 40000,
    description: 'Often called the "American Alps," holding more than 300 active glaciers, steep jagged granite peaks, cascading waterfalls, and brilliant turquoise alpine reservoirs.',
    npsCode: 'noca',
    npsUrl: 'https://www.nps.gov/noca/index.htm',
    highlights: ['Diablo Lake turquoise overlook', 'Cascade Pass & Sahale Arm hike', 'Washington Pass Overlook (Hwy 20)', 'Ross Lake wilderness', 'Stehekin remote village'],
  },
  {
    id: 'olympic',
    name: 'Olympic',
    fullName: 'Olympic National Park',
    state: 'WA',
    stateFull: 'Washington',
    lat: 47.97,
    lng: -123.5,
    establishedYear: 1938,
    areaAcres: 922650,
    areaSqKm: 3733.8,
    annualVisitors: 2950000,
    description: 'Features three distinct ecosystems: wild Pacific coastline with sea stacks, glacier-capped Olympic Mountains, and lush temperate rainforests draped in moss.',
    unescoStatus: 'World Heritage Site',
    npsCode: 'olym',
    npsUrl: 'https://www.nps.gov/olym/index.htm',
    highlights: ['Hoh Rain Forest Hall of Mosses', 'Hurricane Ridge mountain vista', 'Ruby Beach & Rialto Beach sea stacks', 'Lake Crescent crystal waters', 'Sol Duc Falls'],
  },
  {
    id: 'petrified-forest',
    name: 'Petrified Forest',
    fullName: 'Petrified Forest National Park',
    state: 'AZ',
    stateFull: 'Arizona',
    lat: 35.07,
    lng: -109.78,
    establishedYear: 1962,
    areaAcres: 221390,
    areaSqKm: 895.9,
    annualVisitors: 520000,
    description: 'Preserves one of the world\'s largest concentrations of 225-million-year-old colorful petrified wood logs alongside the vibrant badlands of the Painted Desert.',
    npsCode: 'pefo',
    npsUrl: 'https://www.nps.gov/pefo/index.htm',
    highlights: ['Crystal Forest trail', 'Painted Desert Inn & overlooks', 'Blue Mesa badland loop', 'Newspaper Rock petroglyphs', 'Historic Route 66 alignment'],
  },
  {
    id: 'pinnacles',
    name: 'Pinnacles',
    fullName: 'Pinnacles National Park',
    state: 'CA',
    stateFull: 'California',
    lat: 36.48,
    lng: -121.16,
    establishedYear: 2013,
    areaAcres: 26685,
    areaSqKm: 108.0,
    annualVisitors: 340000,
    description: 'The eroded remnants of an extinct 23-million-year-old volcano, famous for talus cave systems, rock climbing crags, and release sites for endangered California condors.',
    npsCode: 'pinn',
    npsUrl: 'https://www.nps.gov/pinn/index.htm',
    highlights: ['California condor soaring over High Peaks', 'Bear Gulch & Balconies talus caves', 'High Peaks Trail steep rock steps', 'Chalone Peak summit'],
  },
  {
    id: 'redwood',
    name: 'Redwood',
    fullName: 'Redwood National and State Parks',
    state: 'CA',
    stateFull: 'California',
    lat: 41.3,
    lng: -124.0,
    establishedYear: 1968,
    areaAcres: 138999,
    areaSqKm: 562.5,
    annualVisitors: 410000,
    description: 'Protects 45% of all remaining coastal redwood old-growth forests, preserving the tallest living trees on the planet alongside 40 miles of wild northern California coast.',
    unescoStatus: 'World Heritage Site',
    npsCode: 'redw',
    npsUrl: 'https://www.nps.gov/redw/index.htm',
    highlights: ['Lady Bird Johnson Grove', 'Fern Canyon lush moss canyon', 'Howland Hill Road old-growth drive', 'Tall Trees Grove', 'Prairie Creek elk herds'],
  },
  {
    id: 'rocky-mountain',
    name: 'Rocky Mountain',
    fullName: 'Rocky Mountain National Park',
    state: 'CO',
    stateFull: 'Colorado',
    lat: 40.4,
    lng: -105.58,
    establishedYear: 1915,
    areaAcres: 265807,
    areaSqKm: 1075.7,
    annualVisitors: 4300000,
    description: 'Bisected by the Continental Divide, showcasing 77 mountain peaks over 12,000 feet, alpine tundra, glacial lakes, and the highest continuous paved highway in North America.',
    unescoStatus: 'Biosphere Reserve',
    npsCode: 'romo',
    npsUrl: 'https://www.nps.gov/romo/index.htm',
    highlights: ['Trail Ridge Road (12,183 ft crest)', 'Bear Lake & Dream Lake trail', 'Longs Peak summit climb (14,259 ft)', 'Alberta Falls', 'Elk rut viewing in Moraine Park'],
  },
  {
    id: 'saguaro',
    name: 'Saguaro',
    fullName: 'Saguaro National Park',
    state: 'AZ',
    stateFull: 'Arizona',
    lat: 32.25,
    lng: -110.5,
    establishedYear: 1994,
    areaAcres: 92867,
    areaSqKm: 375.8,
    annualVisitors: 1000000,
    description: 'Flanking the city of Tucson in two districts (Rincon & Tucson Mountain), preserving dense forests of the giant saguaro cactus, the iconic symbol of the American Southwest.',
    npsCode: 'sagu',
    npsUrl: 'https://www.nps.gov/sagu/index.htm',
    highlights: ['Bajada Loop scenic drive (West)', 'Cactus Forest Drive (East)', 'Signal Hill ancient petroglyphs', 'Valley View overlook', 'Saguaro spring bloom (May/June)'],
  },
  {
    id: 'sequoia',
    name: 'Sequoia',
    fullName: 'Sequoia National Park',
    state: 'CA',
    stateFull: 'California',
    lat: 36.48,
    lng: -118.55,
    establishedYear: 1890,
    areaAcres: 404063,
    areaSqKm: 1635.2,
    annualVisitors: 1150000,
    description: 'Protects the Giant Forest, home to the General Sherman Tree (the largest single-stem tree on Earth by volume), Mount Whitney (14,494 ft), and deep granite canyons.',
    unescoStatus: 'Biosphere Reserve',
    npsCode: 'seki',
    npsUrl: 'https://www.nps.gov/seki/index.htm',
    highlights: ['General Sherman Tree (largest tree by volume)', 'Moro Rock granite stairway climb', 'Tunnel Log drive-through', 'Congress Trail giant sequoia walk', 'Crescent Meadow'],
  },
  {
    id: 'shenandoah',
    name: 'Shenandoah',
    fullName: 'Shenandoah National Park',
    state: 'VA',
    stateFull: 'Virginia',
    lat: 38.53,
    lng: -78.35,
    establishedYear: 1935,
    areaAcres: 200446,
    areaSqKm: 811.2,
    annualVisitors: 1450000,
    description: 'Stretches along the crest of the Blue Ridge Mountains in Virginia, traversed by the 105-mile Skyline Drive with sweeping views of the Shenandoah Valley and Piedmont.',
    npsCode: 'shen',
    npsUrl: 'https://www.nps.gov/shen/index.htm',
    highlights: ['Skyline Drive 105-mile scenic byway', 'Old Rag Mountain rock scramble', 'Dark Hollow Falls', 'Stony Man summit vista', 'Big Meadows deer & stargazing'],
  },
  {
    id: 'theodore-roosevelt',
    name: 'Theodore Roosevelt',
    fullName: 'Theodore Roosevelt National Park',
    state: 'ND',
    stateFull: 'North Dakota',
    lat: 46.97,
    lng: -103.45,
    establishedYear: 1978,
    areaAcres: 70447,
    areaSqKm: 285.1,
    annualVisitors: 750000,
    description: 'Memorializes President Theodore Roosevelt in the colorful badlands where he ranched cattle, home to bison herds, wild horses, prairie dogs, and elk.',
    npsCode: 'thro',
    npsUrl: 'https://www.nps.gov/thro/index.htm',
    highlights: ['South Unit 36-mile scenic drive', 'Wind Canyon sunset overlook', 'Maltese Cross Cabin historic site', 'North Unit Oxbow Overlook', 'Roaming wild horses & bison'],
  },
  {
    id: 'virgin-islands',
    name: 'Virgin Islands',
    fullName: 'Virgin Islands National Park',
    state: 'VI',
    stateFull: 'U.S. Virgin Islands',
    lat: 18.33,
    lng: -64.73,
    establishedYear: 1956,
    areaAcres: 15052,
    areaSqKm: 60.9,
    annualVisitors: 320000,
    description: 'Covers roughly 60% of the island of Saint John, protecting white sand tropical beaches, coral reefs, subtropical moist forests, and Taino petroglyphs.',
    unescoStatus: 'Biosphere Reserve',
    npsCode: 'viis',
    npsUrl: 'https://www.nps.gov/viis/index.htm',
    highlights: ['Trunk Bay underwater snorkeling trail', 'Cinnamon Bay historic campground', 'Reef Bay sugar factory & petroglyphs', 'Ram Head coastal peninsula trail'],
  },
  {
    id: 'voyageurs',
    name: 'Voyageurs',
    fullName: 'Voyageurs National Park',
    state: 'MN',
    stateFull: 'Minnesota',
    lat: 48.5,
    lng: -92.88,
    establishedYear: 1975,
    areaAcres: 218200,
    areaSqKm: 883.0,
    annualVisitors: 220000,
    description: 'A water-based wilderness along the Minnesota-Canada border, preserving expansive interconnected lakes (Rainy, Kabetogama, Namakan), bays, and historic fur-trade routes.',
    npsCode: 'voya',
    npsUrl: 'https://www.nps.gov/voya/index.htm',
    highlights: ['Houseboating on Rainy Lake', 'Ellsworth Rock Gardens', 'Kettle Falls historic hotel', 'Aurora borealis northern lights', 'Island wilderness boat-in campsites'],
  },
  {
    id: 'white-sands',
    name: 'White Sands',
    fullName: 'White Sands National Park',
    state: 'NM',
    stateFull: 'New Mexico',
    lat: 32.78,
    lng: -106.17,
    establishedYear: 2019,
    areaAcres: 146344,
    areaSqKm: 592.2,
    annualVisitors: 730000,
    description: 'The world\'s largest gypsum dunefield covers 275 square miles of the Tularosa Basin, forming shimmering white wave-like dunes that stay cool to the touch.',
    npsCode: 'whsa',
    npsUrl: 'https://www.nps.gov/whsa/index.htm',
    highlights: ['Dunes Drive scenic route', 'Gypsum dune sledding', 'Alkali Flat trail', 'Sunset Stroll ranger walk', 'Fossilized ice-age human footprints'],
  },
  {
    id: 'wind-cave',
    name: 'Wind Cave',
    fullName: 'Wind Cave National Park',
    state: 'SD',
    stateFull: 'South Dakota',
    lat: 43.57,
    lng: -103.48,
    establishedYear: 1903,
    areaAcres: 33970,
    areaSqKm: 137.5,
    annualVisitors: 620000,
    description: 'Recognized for its intricate calcite honeycomb boxwork formations (95% of the world\'s known boxwork) beneath a pristine native mixed-grass prairie teeming with wildlife.',
    npsCode: 'wica',
    npsUrl: 'https://www.nps.gov/wica/index.htm',
    highlights: ['Natural Entrance & Fairgrounds cave tours', 'Rare boxwork calcite formations', 'Rankin Ridge fire tower trail', 'Bison, pronghorn, and prairie dog towns'],
  },
  {
    id: 'wrangell-st-elias',
    name: 'Wrangell–St. Elias',
    fullName: 'Wrangell–St. Elias National Park and Preserve',
    state: 'AK',
    stateFull: 'Alaska',
    lat: 61.0,
    lng: -142.0,
    establishedYear: 1980,
    areaAcres: 13175799,
    areaSqKm: 53320.6,
    annualVisitors: 65000,
    description: 'The largest national park in the United States (equal to six Yellowstones), where four mountain ranges meet, containing nine of North America\'s sixteen highest peaks.',
    unescoStatus: 'World Heritage Site',
    npsCode: 'wrst',
    npsUrl: 'https://www.nps.gov/wrst/index.htm',
    highlights: ['Historic Kennecott copper mill town', 'Root Glacier crampon hike', 'McCarthy Road remote journey', 'Mount Saint Elias (18,008 ft)'],
  },
  {
    id: 'yellowstone',
    name: 'Yellowstone',
    fullName: 'Yellowstone National Park',
    state: 'WY, MT, ID',
    stateFull: 'Wyoming, Montana, Idaho',
    lat: 44.43,
    lng: -110.59,
    establishedYear: 1872,
    areaAcres: 2219791,
    areaSqKm: 8983.2,
    annualVisitors: 4500000,
    description: 'The world\'s first national park, sitting atop a volcanic hotspot with more than 10,000 hydrothermal features, over 500 active geysers, and iconic American wildlife.',
    unescoStatus: 'World Heritage Site',
    npsCode: 'yell',
    npsUrl: 'https://www.nps.gov/yell/index.htm',
    highlights: ['Old Faithful & Upper Geyser Basin', 'Grand Prismatic Spring', 'Grand Canyon of the Yellowstone & Lower Falls', 'Lamar Valley "Serengeti of North America"', 'Mammoth Hot Springs terraces'],
  },
  {
    id: 'yosemite',
    name: 'Yosemite',
    fullName: 'Yosemite National Park',
    state: 'CA',
    stateFull: 'California',
    lat: 37.85,
    lng: -119.54,
    establishedYear: 1890,
    areaAcres: 761748,
    areaSqKm: 3082.7,
    annualVisitors: 3900000,
    description: 'Famed for towering granite monoliths El Capitan and Half Dome, dramatic 2,425-foot Yosemite Falls, deep glacial valleys, and the Mariposa Grove of giant sequoias.',
    unescoStatus: 'World Heritage Site',
    npsCode: 'yose',
    npsUrl: 'https://www.nps.gov/yose/index.htm',
    highlights: ['Yosemite Valley & Tunnel View', 'El Capitan & Half Dome monoliths', 'Yosemite Falls (North America\'s tallest)', 'Glacier Point overlook', 'Tuolumne Meadows & Tioga Road'],
  },
  {
    id: 'zion',
    name: 'Zion',
    fullName: 'Zion National Park',
    state: 'UT',
    stateFull: 'Utah',
    lat: 37.3,
    lng: -113.05,
    establishedYear: 1919,
    areaAcres: 147243,
    areaSqKm: 595.9,
    annualVisitors: 4630000,
    description: 'Prominent 2,000-foot Navajo sandstone cliffs in rich shades of cream, pink, and red rise above the Virgin River canyon, world-renowned for thrilling canyon hiking.',
    npsCode: 'zion',
    npsUrl: 'https://www.nps.gov/zion/index.htm',
    highlights: ['Angels Landing cliffside spine hike', 'The Narrows Virgin River wade', 'Zion Canyon Scenic Drive shuttle', 'Observation Point vista', 'The Subway backcountry slot canyon'],
  },
];

/**
 * Common travel launch hub presets
 */
export const ORIGIN_HUB_PRESETS: OriginHubPreset[] = [
  {
    id: 'las-vegas',
    name: 'Las Vegas, NV',
    state: 'NV',
    lat: 36.1699,
    lng: -115.1398,
    description: 'Premier gateway to the Southwest: Zion, Bryce Canyon, Death Valley, Grand Canyon',
  },
  {
    id: 'denver',
    name: 'Denver, CO',
    state: 'CO',
    lat: 39.7392,
    lng: -104.9903,
    description: 'Gateway to the Rockies: Rocky Mountain, Great Sand Dunes, Black Canyon',
  },
  {
    id: 'salt-lake-city',
    name: 'Salt Lake City, UT',
    state: 'UT',
    lat: 40.7608,
    lng: -111.891,
    description: 'Central hub for Utah\'s Mighty 5 and Grand Teton / Yellowstone',
  },
  {
    id: 'seattle',
    name: 'Seattle, WA',
    state: 'WA',
    lat: 47.6062,
    lng: -122.3321,
    description: 'Pacific Northwest gateway: Mount Rainier, Olympic, North Cascades',
  },
  {
    id: 'san-francisco',
    name: 'San Francisco, CA',
    state: 'CA',
    lat: 37.7749,
    lng: -122.4194,
    description: 'Northern California hub: Yosemite, Pinnacles, Redwood, Lassen Volcanic',
  },
  {
    id: 'los-angeles',
    name: 'Los Angeles, CA',
    state: 'CA',
    lat: 34.0522,
    lng: -118.2437,
    description: 'Southern California hub: Joshua Tree, Channel Islands, Sequoia & Kings Canyon',
  },
  {
    id: 'phoenix',
    name: 'Phoenix, AZ',
    state: 'AZ',
    lat: 33.4484,
    lng: -112.074,
    description: 'Desert gateway: Grand Canyon, Saguaro, Petrified Forest, Joshua Tree',
  },
  {
    id: 'miami',
    name: 'Miami, FL',
    state: 'FL',
    lat: 25.7617,
    lng: -80.1918,
    description: 'Florida gateway: Biscayne, Everglades, Dry Tortugas',
  },
  {
    id: 'new-york',
    name: 'New York, NY',
    state: 'NY',
    lat: 40.7128,
    lng: -74.006,
    description: 'East Coast hub: Shenandoah, Acadia, Cuyahoga Valley',
  },
  {
    id: 'chicago',
    name: 'Chicago, IL',
    state: 'IL',
    lat: 41.8781,
    lng: -87.6298,
    description: 'Midwest hub: Indiana Dunes, Gateway Arch, Cuyahoga Valley, Mammoth Cave',
  },
  {
    id: 'anchorage',
    name: 'Anchorage, AK',
    state: 'AK',
    lat: 61.2181,
    lng: -149.9003,
    description: 'Alaska hub: Kenai Fjords, Denali, Wrangell–St. Elias, Lake Clark, Katmai',
  },
  {
    id: 'honolulu',
    name: 'Honolulu, HI',
    state: 'HI',
    lat: 21.3069,
    lng: -157.8583,
    description: 'Hawaii hub: Haleakalā (Maui), Hawaiʻi Volcanoes (Big Island)',
  },
];

/**
 * Converts degrees into 16-point cardinal compass directions
 */
export function get16PointCardinal(degrees: number): string {
  const normalized = ((degrees % 360) + 360) % 360;
  const directions = [
    'N', 'NNE', 'NE', 'ENE',
    'E', 'ESE', 'SE', 'SSE',
    'S', 'SSW', 'SW', 'WSW',
    'W', 'WNW', 'NW', 'NNW',
  ];
  const index = Math.round(normalized / 22.5) % 16;
  return directions[index];
}

/**
 * Calculates estimated driving distance and time from direct straight-line distance
 * Road tortuosity factor: ~1.28x direct distance
 * Average highway driving speed: ~58 mph (93 km/h)
 */
export function estimateRoadTravel(distanceMiles: number): { estimatedDriveMiles: number; estimatedDriveHours: number } {
  // Road factor ranges between 1.25 to 1.35 depending on geography
  const factor = 1.28;
  const estimatedDriveMiles = Math.round(distanceMiles * factor);
  const estimatedDriveHours = parseFloat((estimatedDriveMiles / 58).toFixed(1));
  return { estimatedDriveMiles, estimatedDriveHours };
}

/**
 * Finds the nearest national parks to any given origin coordinate
 */
export function findNearestNationalParks(
  originLat: number,
  originLng: number,
  options: ParkFilterOptions = {}
): NearestParkResult[] {
  const { maxResults = 10, maxRadiusMiles, state, searchQuery } = options;

  let candidates = [...US_NATIONAL_PARKS];

  // Optional state filter
  if (state && state !== 'ALL') {
    const s = state.toUpperCase();
    candidates = candidates.filter((p) => p.state.toUpperCase().includes(s));
  }

  // Optional search query (name or highlight)
  if (searchQuery && searchQuery.trim()) {
    const q = searchQuery.toLowerCase().trim();
    candidates = candidates.filter(
      (p) =>
        p.name.toLowerCase().includes(q) ||
        p.fullName.toLowerCase().includes(q) ||
        p.stateFull.toLowerCase().includes(q) ||
        p.state.toLowerCase().includes(q) ||
        p.highlights.some((h) => h.toLowerCase().includes(q))
    );
  }

  const results: NearestParkResult[] = candidates.map((park) => {
    const geodesic = calculateGeodesic(
      { lat: originLat, lng: originLng },
      { lat: park.lat, lng: park.lng }
    );

    const distanceMeters = geodesic.distanceMeters;
    const distanceMiles = parseFloat((distanceMeters / 1609.344).toFixed(1));
    const distanceKm = parseFloat((distanceMeters / 1000).toFixed(1));
    const bearingDegrees = Math.round(geodesic.initialBearingDeg);
    const cardinalBearing = get16PointCardinal(bearingDegrees);
    const { estimatedDriveMiles, estimatedDriveHours } = estimateRoadTravel(distanceMiles);

    return {
      park,
      distanceMeters,
      distanceMiles,
      distanceKm,
      bearingDegrees,
      cardinalBearing,
      estimatedDriveMiles,
      estimatedDriveHours,
    };
  });

  // Sort by straight-line geodesic distance ascending
  results.sort((a, b) => a.distanceMeters - b.distanceMeters);

  // Filter by max radius if provided
  let filtered = results;
  if (maxRadiusMiles && maxRadiusMiles > 0) {
    filtered = filtered.filter((r) => r.distanceMiles <= maxRadiusMiles);
  }

  // Cap at maxResults if provided
  if (maxResults && maxResults > 0) {
    filtered = filtered.slice(0, maxResults);
  }

  return filtered;
}

/**
 * Generates an RFC-4180 CSV export of nearest national parks results
 */
export function exportNearestParksToCSV(
  results: NearestParkResult[],
  originLabel: string = 'Custom Origin'
): string {
  const headers = [
    'Rank',
    'National Park',
    'State',
    'Direct Distance (Miles)',
    'Direct Distance (KM)',
    'Bearing (Degrees)',
    'Cardinal Direction',
    'Estimated Drive (Miles)',
    'Estimated Drive (Hours)',
    'Established Year',
    'Area (Acres)',
    'Annual Visitors',
    'UNESCO Status',
    'NPS URL',
  ];

  const escapeCSV = (val: string | number | undefined | null) => {
    if (val === undefined || val === null) return '""';
    const str = String(val);
    if (str.includes(',') || str.includes('"') || str.includes('\n')) {
      return `"${str.replace(/"/g, '""')}"`;
    }
    return `"${str}"`;
  };

  const rows = results.map((r, index) => [
    index + 1,
    escapeCSV(r.park.fullName),
    escapeCSV(r.park.state),
    r.distanceMiles,
    r.distanceKm,
    r.bearingDegrees,
    escapeCSV(r.cardinalBearing),
    r.estimatedDriveMiles,
    r.estimatedDriveHours,
    r.park.establishedYear,
    r.park.areaAcres,
    r.park.annualVisitors,
    escapeCSV(r.park.unescoStatus || 'None'),
    escapeCSV(r.park.npsUrl),
  ]);

  const comments = `# GeoMapSuite Find Nearest National Park Export\n# Origin: ${originLabel}\n# Generated: ${new Date().toISOString()}\n`;
  const csvContent = comments + [headers.join(','), ...rows.map((row) => row.join(','))].join('\n');
  return csvContent;
}

/**
 * Formats a plain text itinerary / briefing snippet for clipboard copying
 */
export function formatParkBriefing(
  result: NearestParkResult,
  rank: number = 1,
  originLabel: string = 'Your Location'
): string {
  const p = result.park;
  return `🌲 Rank #${rank}: ${p.fullName} (${p.state})
📍 From: ${originLabel}
📏 Direct Distance: ${result.distanceMiles.toLocaleString()} miles (${result.distanceKm.toLocaleString()} km)
🧭 Direction: ${result.bearingDegrees}° (${result.cardinalBearing})
🚗 Est. Drive: ~${result.estimatedDriveMiles.toLocaleString()} miles (~${result.estimatedDriveHours} hrs driving)
📅 Established: ${p.establishedYear} | 📐 Area: ${p.areaAcres.toLocaleString()} acres (${p.areaSqKm.toLocaleString()} km²)
👥 Annual Visitors: ~${(p.annualVisitors / 1000000).toFixed(2)}M
⭐ Highlights: ${p.highlights.join(', ')}
🔗 Official NPS Website: ${p.npsUrl}`;
}
